export const payoutTransactionColumnHeaders = [
  { name: "Provider", key: "provider" },
  { name: "Provider TRANS", key: "providerTxnId", width: 220 },
  {
    name: "TRANS date",
    key: "date",
    width: 200
  },
  { name: "Type", key: "type", width: 200 },
  { name: "Status", key: "status" },
  { name: "Code", key: "code" },
  { name: "Reference id", key: "refId", width: 220 },
  { name: "Invoice", key: "invoice", width: 200 }
  // {
  //     name: "Commerce  Order",
  //     key: "commerceOrderIncrementId",
  //     width: 200,
  // },
  // { name: "Commerce TRANS", key: "commerceTxnId", width: 220 },
  // { name: "Pay Method", key: "payMethod", width: 150 },
  // {
  //     name: "TRANS AMT",
  //     key: "amount",
  //     width: 120,
  //     align: "end",
  // },
  // { name: "cur", key: "currency" },
  // {
  //     name: "pending",
  //     key: "pendingAmt",
  //     width: 120,
  //     align: "end",
  // },
  // { name: "cur", key: "pendingCurrency" },
  // {
  //     name: "seller AMT",
  //     key: "sellerAmt",
  //     width: 120,
  //     align: "end",
  // },
  // { name: "cur", key: "sellerCurrency" },
  // {
  //     name: "partner fee",
  //     key: "partnerFee",
  //     width: 120,
  //     align: "end",
  // },
  // { name: "cur", key: "partnerCurrency" },
  // {
  //     name: "Prov Fees",
  //     key: "providerFee",
  //     width: 120,
  //     align: "end",
  // },
  // { name: "cur", key: "providerCurrency" },
  // { name: "fee %", key: "feePct", align: "end" },
  // { name: "fixed fee", key: "fixedFee", align: "end"},
  // { name: "CHBK fee", key: "chargebackFee", width: 120, align: "end" },
  // { name: "cur", key: "chargebackCurrency" },
  // {
  //     name: "Hold AMT",
  //     key: "holdAmount",
  //     width: 120,
  //     align: "end",
  // },
  // { name: "cur", key: "holdCurrency" },
  // {
  //     name: "recoup AMT",
  //     key: "recoupAmount",
  //     width: 120,
  //     align: "end",
  // },
  // { name: "cur", key: "recoupCurrency" },
];
